# 🐚 Paguro - Docker Compose per Villa Celi
# Setup: API Paguro + Ollama per Palinuro, Cilento

services:
  # 🐚 Paguro API - Receptionist Virtuale
  paguro-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paguro-api-villaceli
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DB_PATH=/app/data/affitti2025.db
      - OLLAMA_URL=http://ollama:11434/api/generate
      - MODEL=llama3.2:1b
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - VILLA_CELI_FRONTEND=https://www.villaceli.it
      - API_BASE_URL=https://api.viamerano24.it/api
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/cache:/app/cache
    depends_on:
      - ollama
    networks:
      - paguro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 🤖 Ollama - AI Engine per Paguro
  ollama:
    build:
      context: ./backend
      dockerfile: ollama.Dockerfile
    container_name: paguro-ollama-villaceli
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3.2:1b
      - OLLAMA_GPU=false
      - CUDA_VISIBLE_DEVICES=""
    networks:
      - paguro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# 📡 Network per comunicazione interna Paguro
networks:
  paguro-network:
    driver: bridge
    name: paguro-villaceli-network

# 💾 Volumi persistenti per Paguro
volumes:
  ollama-data:
    name: paguro-ollama-villaceli-data
    driver: local
