# 🐚 Paguro - Docker Compose SEMPLICE per Villa Celi
# Setup veloce per development e testing
version: '3.8'

services:
  # 🐚 Paguro API - Receptionist Virtuale
  paguro-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paguro-api-simple
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_PATH=/app/data/affitti2025.db
      - OLLAMA_URL=http://ollama:11434/api/generate
      - MODEL=llama3.2:1b
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    depends_on:
      - ollama
    networks:
      - paguro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 🤖 Ollama - AI Engine per Paguro (CPU ottimizzato)
  ollama:
    image: ollama/ollama:latest
    container_name: paguro-ollama-simple
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=llama3.2:1b
      - OLLAMA_GPU=false
      - CUDA_VISIBLE_DEVICES=""
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ollama-data:/root/.ollama
      - ./scripts:/scripts:ro
    networks:
      - paguro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

# 📡 Network dedicato per comunicazione Paguro
networks:
  paguro-network:
    driver: bridge
    name: paguro-simple-network

# 💾 Volumi persistenti per Paguro
volumes:
  ollama-data:
    name: paguro-ollama-simple-data
    driver: local
